apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp-lbs
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webapp
  type: LoadBalancer
  loadBalancerIP: 10.2.100.130