apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dmz
spec:
  addresses:
  - "10.2.100.100-10.2.100.120"
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: dmzadvert
spec:
  ipAddressPools:
  - dmz
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: ns-k8swrk-01.l1-nak.local
  - matchLabels:
      kubernetes.io/hostname: ns-k8swrk-02.l1-nak.local
  - matchLabels:
      kubernetes.io/hostname: ns-k8swrk-03.l1-nak.local